package seguranca.model;
// Generated 13/12/2015 09:40:17 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbLog generated by hbm2java
 */
@Entity
@Table(name="tb_log"
    ,catalog="bd_prototipo"
)
public class TbLog  implements java.io.Serializable {


     private Integer idtLog;
     private TbUsuario tbUsuario;
     private String dscOperacao;
     private String tipOperacao;

    public TbLog() {
    }

    public TbLog(TbUsuario tbUsuario, String dscOperacao, String tipOperacao) {
       this.tbUsuario = tbUsuario;
       this.dscOperacao = dscOperacao;
       this.tipOperacao = tipOperacao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_log", unique=true, nullable=false)
    public Integer getIdtLog() {
        return this.idtLog;
    }
    
    public void setIdtLog(Integer idtLog) {
        this.idtLog = idtLog;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_usuario", nullable=false)
    public TbUsuario getTbUsuario() {
        return this.tbUsuario;
    }
    
    public void setTbUsuario(TbUsuario tbUsuario) {
        this.tbUsuario = tbUsuario;
    }
    
    @Column(name="dsc_operacao", nullable=false, length=65535)
    public String getDscOperacao() {
        return this.dscOperacao;
    }
    
    public void setDscOperacao(String dscOperacao) {
        this.dscOperacao = dscOperacao;
    }
    
    @Column(name="tip_operacao", nullable=false, length=30)
    public String getTipOperacao() {
        return this.tipOperacao;
    }
    
    public void setTipOperacao(String tipOperacao) {
        this.tipOperacao = tipOperacao;
    }




}


