package seguranca.model;
// Generated 13/12/2015 09:40:17 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbPerfil generated by hbm2java
 */
@Entity
@Table(name="tb_perfil"
    ,catalog="bd_prototipo"
)
public class TbPerfil  implements java.io.Serializable {


     private Integer idtPerfil;
     private String nmePerfil;
     private String sglPerfil;
     private String usrPerfilCad;
     private Date dtaPerfilCad;
     private String usrPerfilMod;
     private Date dtaPerfilMod;
     private Integer ordPerfil;
     private Set<TaPrivilegio> taPrivilegios = new HashSet<TaPrivilegio>(0);
     private Set<TbUsuario> tbUsuarios = new HashSet<TbUsuario>(0);

    public TbPerfil() {
    }

	
    public TbPerfil(String nmePerfil, String usrPerfilCad, Date dtaPerfilCad) {
        this.nmePerfil = nmePerfil;
        this.usrPerfilCad = usrPerfilCad;
        this.dtaPerfilCad = dtaPerfilCad;
    }
    public TbPerfil(String nmePerfil, String sglPerfil, String usrPerfilCad, Date dtaPerfilCad, String usrPerfilMod, Date dtaPerfilMod, Integer ordPerfil, Set<TaPrivilegio> taPrivilegios, Set<TbUsuario> tbUsuarios) {
       this.nmePerfil = nmePerfil;
       this.sglPerfil = sglPerfil;
       this.usrPerfilCad = usrPerfilCad;
       this.dtaPerfilCad = dtaPerfilCad;
       this.usrPerfilMod = usrPerfilMod;
       this.dtaPerfilMod = dtaPerfilMod;
       this.ordPerfil = ordPerfil;
       this.taPrivilegios = taPrivilegios;
       this.tbUsuarios = tbUsuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_perfil", unique=true, nullable=false)
    public Integer getIdtPerfil() {
        return this.idtPerfil;
    }
    
    public void setIdtPerfil(Integer idtPerfil) {
        this.idtPerfil = idtPerfil;
    }
    
    @Column(name="nme_perfil", nullable=false, length=80)
    public String getNmePerfil() {
        return this.nmePerfil;
    }
    
    public void setNmePerfil(String nmePerfil) {
        this.nmePerfil = nmePerfil;
    }
    
    @Column(name="sgl_perfil", length=30)
    public String getSglPerfil() {
        return this.sglPerfil;
    }
    
    public void setSglPerfil(String sglPerfil) {
        this.sglPerfil = sglPerfil;
    }
    
    @Column(name="usr_perfil_cad", nullable=false, length=20)
    public String getUsrPerfilCad() {
        return this.usrPerfilCad;
    }
    
    public void setUsrPerfilCad(String usrPerfilCad) {
        this.usrPerfilCad = usrPerfilCad;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dta_perfil_cad", nullable=false, length=10)
    public Date getDtaPerfilCad() {
        return this.dtaPerfilCad;
    }
    
    public void setDtaPerfilCad(Date dtaPerfilCad) {
        this.dtaPerfilCad = dtaPerfilCad;
    }
    
    @Column(name="usr_perfil_mod", length=20)
    public String getUsrPerfilMod() {
        return this.usrPerfilMod;
    }
    
    public void setUsrPerfilMod(String usrPerfilMod) {
        this.usrPerfilMod = usrPerfilMod;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dta_perfil_mod", length=10)
    public Date getDtaPerfilMod() {
        return this.dtaPerfilMod;
    }
    
    public void setDtaPerfilMod(Date dtaPerfilMod) {
        this.dtaPerfilMod = dtaPerfilMod;
    }
    
    @Column(name="ord_perfil")
    public Integer getOrdPerfil() {
        return this.ordPerfil;
    }
    
    public void setOrdPerfil(Integer ordPerfil) {
        this.ordPerfil = ordPerfil;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbPerfil")
    public Set<TaPrivilegio> getTaPrivilegios() {
        return this.taPrivilegios;
    }
    
    public void setTaPrivilegios(Set<TaPrivilegio> taPrivilegios) {
        this.taPrivilegios = taPrivilegios;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbPerfil")
    public Set<TbUsuario> getTbUsuarios() {
        return this.tbUsuarios;
    }
    
    public void setTbUsuarios(Set<TbUsuario> tbUsuarios) {
        this.tbUsuarios = tbUsuarios;
    }




}


